name: assetsAPI
channels:
- defaults
dependencies:
- click=6.7=py36_0
- flask=0.12.1=py36_0
- itsdangerous=0.24=py36_0
- jinja2=2.9.6=py36_0
- markupsafe=0.23=py36_2
- openssl=1.0.2k=2
- pip=9.0.1=py36_1
- py=1.4.33=py36_0
- pytest=3.0.7=py36_0
- python=3.6.1=2
- readline=6.2=2
- requests=2.14.2=py36_0
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- werkzeug=0.12.1=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - flask-httpauth==3.2.2

